version: '3.8'

services:
  pollingapp-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: pollingapp-api
    container_name: pollingapp
    ports:
      - '5005:5005'
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: pollingapp_db
    environment:
      POSTGRES_DB: pollapp
      POSTGRES_USER: $DS_USERNAME
      POSTGRES_PASSWORD: $DS_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data

  dev:
    image: gradle:6.7.1-jdk8
    container_name: pollapp_dev
    env_file:
      - .env
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - $PWD:/app
      - gradle_volume:/home/gradle/.gradle
    user: gradle
    working_dir: /app
    command: sh -c "gradle build -xtest --continuous & gradle bootRun"
    depends_on:
      - db

volumes:
  gradle_volume:
